# Autogenerated wrapper script for abPOA_jll for x86_64-linux-gnu
export abpoa, libabpoa

using Zlib_jll
JLLWrappers.@generate_wrapper_header("abPOA")
JLLWrappers.@declare_library_product(libabpoa, "libabpoa.so")
JLLWrappers.@declare_executable_product(abpoa)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libabpoa,
        "lib/libabpoa.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        abpoa,
        "bin/abpoa",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
